name: Deploy minified files to FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build (minify) CSS & JS
        run: npx gulp styles && npx gulp scripts

      - name: Upload minified files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Cesta ke generovaným minifikovaným souborům (output/...) 
          local-dir: ./output/
          server-dir: /output/
          exclude: |
            **/*.css
            **/*.js
            !**/*.min.css
            !**/*.min.js